// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: demo.proto

package com.xuan.protobuf_pojo;

public final class DemoProto {
  private DemoProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  /**
   * Protobuf enum {@code TargetType}
   */
  public enum TargetType
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <pre>
     ** 错误类型或无法攻击
     * </pre>
     *
     * <code>errorTarget = 0;</code>
     */
    errorTarget(0),
    /**
     * <pre>
     ** 地面
     * </pre>
     *
     * <code>ground = 1;</code>
     */
    ground(1),
    /**
     * <pre>
     ** 天空 
     * </pre>
     *
     * <code>sky = 2;</code>
     */
    sky(2),
    /**
     * <pre>
     ** 天空和地面 
     * </pre>
     *
     * <code>groundAndSky = 3;</code>
     */
    groundAndSky(3),
    /**
     * <pre>
     ** 建筑 
     * </pre>
     *
     * <code>building = 4;</code>
     */
    building(4),
    UNRECOGNIZED(-1),
    ;

    /**
     * <pre>
     ** 错误类型或无法攻击
     * </pre>
     *
     * <code>errorTarget = 0;</code>
     */
    public static final int errorTarget_VALUE = 0;
    /**
     * <pre>
     ** 地面
     * </pre>
     *
     * <code>ground = 1;</code>
     */
    public static final int ground_VALUE = 1;
    /**
     * <pre>
     ** 天空 
     * </pre>
     *
     * <code>sky = 2;</code>
     */
    public static final int sky_VALUE = 2;
    /**
     * <pre>
     ** 天空和地面 
     * </pre>
     *
     * <code>groundAndSky = 3;</code>
     */
    public static final int groundAndSky_VALUE = 3;
    /**
     * <pre>
     ** 建筑 
     * </pre>
     *
     * <code>building = 4;</code>
     */
    public static final int building_VALUE = 4;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static TargetType valueOf(int value) {
      return forNumber(value);
    }

    public static TargetType forNumber(int value) {
      switch (value) {
        case 0: return errorTarget;
        case 1: return ground;
        case 2: return sky;
        case 3: return groundAndSky;
        case 4: return building;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<TargetType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        TargetType> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<TargetType>() {
            public TargetType findValueByNumber(int number) {
              return TargetType.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.xuan.protobuf_pojo.DemoProto.getDescriptor().getEnumTypes().get(0);
    }

    private static final TargetType[] VALUES = values();

    public static TargetType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private TargetType(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:TargetType)
  }

  public interface ClazzOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Clazz)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .Classmate classmate = 1;</code>
     */
    java.util.List<com.xuan.protobuf_pojo.DemoProto.Classmate> 
        getClassmateList();
    /**
     * <code>repeated .Classmate classmate = 1;</code>
     */
    com.xuan.protobuf_pojo.DemoProto.Classmate getClassmate(int index);
    /**
     * <code>repeated .Classmate classmate = 1;</code>
     */
    int getClassmateCount();
    /**
     * <code>repeated .Classmate classmate = 1;</code>
     */
    java.util.List<? extends com.xuan.protobuf_pojo.DemoProto.ClassmateOrBuilder> 
        getClassmateOrBuilderList();
    /**
     * <code>repeated .Classmate classmate = 1;</code>
     */
    com.xuan.protobuf_pojo.DemoProto.ClassmateOrBuilder getClassmateOrBuilder(
        int index);
  }
  /**
   * <pre>
   ** 班级 
   * </pre>
   *
   * Protobuf type {@code Clazz}
   */
  public  static final class Clazz extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Clazz)
      ClazzOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Clazz.newBuilder() to construct.
    private Clazz(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Clazz() {
      classmate_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Clazz(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                classmate_ = new java.util.ArrayList<com.xuan.protobuf_pojo.DemoProto.Classmate>();
                mutable_bitField0_ |= 0x00000001;
              }
              classmate_.add(
                  input.readMessage(com.xuan.protobuf_pojo.DemoProto.Classmate.parser(), extensionRegistry));
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) != 0)) {
          classmate_ = java.util.Collections.unmodifiableList(classmate_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.xuan.protobuf_pojo.DemoProto.internal_static_Clazz_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.xuan.protobuf_pojo.DemoProto.internal_static_Clazz_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.xuan.protobuf_pojo.DemoProto.Clazz.class, com.xuan.protobuf_pojo.DemoProto.Clazz.Builder.class);
    }

    public static final int CLASSMATE_FIELD_NUMBER = 1;
    private java.util.List<com.xuan.protobuf_pojo.DemoProto.Classmate> classmate_;
    /**
     * <code>repeated .Classmate classmate = 1;</code>
     */
    public java.util.List<com.xuan.protobuf_pojo.DemoProto.Classmate> getClassmateList() {
      return classmate_;
    }
    /**
     * <code>repeated .Classmate classmate = 1;</code>
     */
    public java.util.List<? extends com.xuan.protobuf_pojo.DemoProto.ClassmateOrBuilder> 
        getClassmateOrBuilderList() {
      return classmate_;
    }
    /**
     * <code>repeated .Classmate classmate = 1;</code>
     */
    public int getClassmateCount() {
      return classmate_.size();
    }
    /**
     * <code>repeated .Classmate classmate = 1;</code>
     */
    public com.xuan.protobuf_pojo.DemoProto.Classmate getClassmate(int index) {
      return classmate_.get(index);
    }
    /**
     * <code>repeated .Classmate classmate = 1;</code>
     */
    public com.xuan.protobuf_pojo.DemoProto.ClassmateOrBuilder getClassmateOrBuilder(
        int index) {
      return classmate_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < classmate_.size(); i++) {
        output.writeMessage(1, classmate_.get(i));
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < classmate_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, classmate_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.xuan.protobuf_pojo.DemoProto.Clazz)) {
        return super.equals(obj);
      }
      com.xuan.protobuf_pojo.DemoProto.Clazz other = (com.xuan.protobuf_pojo.DemoProto.Clazz) obj;

      if (!getClassmateList()
          .equals(other.getClassmateList())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getClassmateCount() > 0) {
        hash = (37 * hash) + CLASSMATE_FIELD_NUMBER;
        hash = (53 * hash) + getClassmateList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.xuan.protobuf_pojo.DemoProto.Clazz parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.xuan.protobuf_pojo.DemoProto.Clazz parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.xuan.protobuf_pojo.DemoProto.Clazz parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.xuan.protobuf_pojo.DemoProto.Clazz parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.xuan.protobuf_pojo.DemoProto.Clazz parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.xuan.protobuf_pojo.DemoProto.Clazz parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.xuan.protobuf_pojo.DemoProto.Clazz parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.xuan.protobuf_pojo.DemoProto.Clazz parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.xuan.protobuf_pojo.DemoProto.Clazz parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.xuan.protobuf_pojo.DemoProto.Clazz parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.xuan.protobuf_pojo.DemoProto.Clazz parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.xuan.protobuf_pojo.DemoProto.Clazz parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.xuan.protobuf_pojo.DemoProto.Clazz prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     ** 班级 
     * </pre>
     *
     * Protobuf type {@code Clazz}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Clazz)
        com.xuan.protobuf_pojo.DemoProto.ClazzOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.xuan.protobuf_pojo.DemoProto.internal_static_Clazz_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.xuan.protobuf_pojo.DemoProto.internal_static_Clazz_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.xuan.protobuf_pojo.DemoProto.Clazz.class, com.xuan.protobuf_pojo.DemoProto.Clazz.Builder.class);
      }

      // Construct using com.xuan.protobuf_pojo.DemoProto.Clazz.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getClassmateFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        if (classmateBuilder_ == null) {
          classmate_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          classmateBuilder_.clear();
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.xuan.protobuf_pojo.DemoProto.internal_static_Clazz_descriptor;
      }

      @java.lang.Override
      public com.xuan.protobuf_pojo.DemoProto.Clazz getDefaultInstanceForType() {
        return com.xuan.protobuf_pojo.DemoProto.Clazz.getDefaultInstance();
      }

      @java.lang.Override
      public com.xuan.protobuf_pojo.DemoProto.Clazz build() {
        com.xuan.protobuf_pojo.DemoProto.Clazz result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.xuan.protobuf_pojo.DemoProto.Clazz buildPartial() {
        com.xuan.protobuf_pojo.DemoProto.Clazz result = new com.xuan.protobuf_pojo.DemoProto.Clazz(this);
        int from_bitField0_ = bitField0_;
        if (classmateBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0)) {
            classmate_ = java.util.Collections.unmodifiableList(classmate_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.classmate_ = classmate_;
        } else {
          result.classmate_ = classmateBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.xuan.protobuf_pojo.DemoProto.Clazz) {
          return mergeFrom((com.xuan.protobuf_pojo.DemoProto.Clazz)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.xuan.protobuf_pojo.DemoProto.Clazz other) {
        if (other == com.xuan.protobuf_pojo.DemoProto.Clazz.getDefaultInstance()) return this;
        if (classmateBuilder_ == null) {
          if (!other.classmate_.isEmpty()) {
            if (classmate_.isEmpty()) {
              classmate_ = other.classmate_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureClassmateIsMutable();
              classmate_.addAll(other.classmate_);
            }
            onChanged();
          }
        } else {
          if (!other.classmate_.isEmpty()) {
            if (classmateBuilder_.isEmpty()) {
              classmateBuilder_.dispose();
              classmateBuilder_ = null;
              classmate_ = other.classmate_;
              bitField0_ = (bitField0_ & ~0x00000001);
              classmateBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getClassmateFieldBuilder() : null;
            } else {
              classmateBuilder_.addAllMessages(other.classmate_);
            }
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.xuan.protobuf_pojo.DemoProto.Clazz parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.xuan.protobuf_pojo.DemoProto.Clazz) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<com.xuan.protobuf_pojo.DemoProto.Classmate> classmate_ =
        java.util.Collections.emptyList();
      private void ensureClassmateIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          classmate_ = new java.util.ArrayList<com.xuan.protobuf_pojo.DemoProto.Classmate>(classmate_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.xuan.protobuf_pojo.DemoProto.Classmate, com.xuan.protobuf_pojo.DemoProto.Classmate.Builder, com.xuan.protobuf_pojo.DemoProto.ClassmateOrBuilder> classmateBuilder_;

      /**
       * <code>repeated .Classmate classmate = 1;</code>
       */
      public java.util.List<com.xuan.protobuf_pojo.DemoProto.Classmate> getClassmateList() {
        if (classmateBuilder_ == null) {
          return java.util.Collections.unmodifiableList(classmate_);
        } else {
          return classmateBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .Classmate classmate = 1;</code>
       */
      public int getClassmateCount() {
        if (classmateBuilder_ == null) {
          return classmate_.size();
        } else {
          return classmateBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .Classmate classmate = 1;</code>
       */
      public com.xuan.protobuf_pojo.DemoProto.Classmate getClassmate(int index) {
        if (classmateBuilder_ == null) {
          return classmate_.get(index);
        } else {
          return classmateBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .Classmate classmate = 1;</code>
       */
      public Builder setClassmate(
          int index, com.xuan.protobuf_pojo.DemoProto.Classmate value) {
        if (classmateBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureClassmateIsMutable();
          classmate_.set(index, value);
          onChanged();
        } else {
          classmateBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .Classmate classmate = 1;</code>
       */
      public Builder setClassmate(
          int index, com.xuan.protobuf_pojo.DemoProto.Classmate.Builder builderForValue) {
        if (classmateBuilder_ == null) {
          ensureClassmateIsMutable();
          classmate_.set(index, builderForValue.build());
          onChanged();
        } else {
          classmateBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Classmate classmate = 1;</code>
       */
      public Builder addClassmate(com.xuan.protobuf_pojo.DemoProto.Classmate value) {
        if (classmateBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureClassmateIsMutable();
          classmate_.add(value);
          onChanged();
        } else {
          classmateBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .Classmate classmate = 1;</code>
       */
      public Builder addClassmate(
          int index, com.xuan.protobuf_pojo.DemoProto.Classmate value) {
        if (classmateBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureClassmateIsMutable();
          classmate_.add(index, value);
          onChanged();
        } else {
          classmateBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .Classmate classmate = 1;</code>
       */
      public Builder addClassmate(
          com.xuan.protobuf_pojo.DemoProto.Classmate.Builder builderForValue) {
        if (classmateBuilder_ == null) {
          ensureClassmateIsMutable();
          classmate_.add(builderForValue.build());
          onChanged();
        } else {
          classmateBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Classmate classmate = 1;</code>
       */
      public Builder addClassmate(
          int index, com.xuan.protobuf_pojo.DemoProto.Classmate.Builder builderForValue) {
        if (classmateBuilder_ == null) {
          ensureClassmateIsMutable();
          classmate_.add(index, builderForValue.build());
          onChanged();
        } else {
          classmateBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Classmate classmate = 1;</code>
       */
      public Builder addAllClassmate(
          java.lang.Iterable<? extends com.xuan.protobuf_pojo.DemoProto.Classmate> values) {
        if (classmateBuilder_ == null) {
          ensureClassmateIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, classmate_);
          onChanged();
        } else {
          classmateBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .Classmate classmate = 1;</code>
       */
      public Builder clearClassmate() {
        if (classmateBuilder_ == null) {
          classmate_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          classmateBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .Classmate classmate = 1;</code>
       */
      public Builder removeClassmate(int index) {
        if (classmateBuilder_ == null) {
          ensureClassmateIsMutable();
          classmate_.remove(index);
          onChanged();
        } else {
          classmateBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .Classmate classmate = 1;</code>
       */
      public com.xuan.protobuf_pojo.DemoProto.Classmate.Builder getClassmateBuilder(
          int index) {
        return getClassmateFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .Classmate classmate = 1;</code>
       */
      public com.xuan.protobuf_pojo.DemoProto.ClassmateOrBuilder getClassmateOrBuilder(
          int index) {
        if (classmateBuilder_ == null) {
          return classmate_.get(index);  } else {
          return classmateBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .Classmate classmate = 1;</code>
       */
      public java.util.List<? extends com.xuan.protobuf_pojo.DemoProto.ClassmateOrBuilder> 
           getClassmateOrBuilderList() {
        if (classmateBuilder_ != null) {
          return classmateBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(classmate_);
        }
      }
      /**
       * <code>repeated .Classmate classmate = 1;</code>
       */
      public com.xuan.protobuf_pojo.DemoProto.Classmate.Builder addClassmateBuilder() {
        return getClassmateFieldBuilder().addBuilder(
            com.xuan.protobuf_pojo.DemoProto.Classmate.getDefaultInstance());
      }
      /**
       * <code>repeated .Classmate classmate = 1;</code>
       */
      public com.xuan.protobuf_pojo.DemoProto.Classmate.Builder addClassmateBuilder(
          int index) {
        return getClassmateFieldBuilder().addBuilder(
            index, com.xuan.protobuf_pojo.DemoProto.Classmate.getDefaultInstance());
      }
      /**
       * <code>repeated .Classmate classmate = 1;</code>
       */
      public java.util.List<com.xuan.protobuf_pojo.DemoProto.Classmate.Builder> 
           getClassmateBuilderList() {
        return getClassmateFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.xuan.protobuf_pojo.DemoProto.Classmate, com.xuan.protobuf_pojo.DemoProto.Classmate.Builder, com.xuan.protobuf_pojo.DemoProto.ClassmateOrBuilder> 
          getClassmateFieldBuilder() {
        if (classmateBuilder_ == null) {
          classmateBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              com.xuan.protobuf_pojo.DemoProto.Classmate, com.xuan.protobuf_pojo.DemoProto.Classmate.Builder, com.xuan.protobuf_pojo.DemoProto.ClassmateOrBuilder>(
                  classmate_,
                  ((bitField0_ & 0x00000001) != 0),
                  getParentForChildren(),
                  isClean());
          classmate_ = null;
        }
        return classmateBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:Clazz)
    }

    // @@protoc_insertion_point(class_scope:Clazz)
    private static final com.xuan.protobuf_pojo.DemoProto.Clazz DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.xuan.protobuf_pojo.DemoProto.Clazz();
    }

    public static com.xuan.protobuf_pojo.DemoProto.Clazz getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Clazz>
        PARSER = new com.google.protobuf.AbstractParser<Clazz>() {
      @java.lang.Override
      public Clazz parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Clazz(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Clazz> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Clazz> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.xuan.protobuf_pojo.DemoProto.Clazz getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface ClassmateOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Classmate)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     ** 名字 
     * </pre>
     *
     * <code>string name = 1;</code>
     */
    java.lang.String getName();
    /**
     * <pre>
     ** 名字 
     * </pre>
     *
     * <code>string name = 1;</code>
     */
    com.google.protobuf.ByteString
        getNameBytes();

    /**
     * <pre>
     ** 性别 
     * </pre>
     *
     * <code>bool sex = 2;</code>
     */
    boolean getSex();
  }
  /**
   * <pre>
   ** 同学 
   * </pre>
   *
   * Protobuf type {@code Classmate}
   */
  public  static final class Classmate extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Classmate)
      ClassmateOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Classmate.newBuilder() to construct.
    private Classmate(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Classmate() {
      name_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Classmate(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              name_ = s;
              break;
            }
            case 16: {

              sex_ = input.readBool();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.xuan.protobuf_pojo.DemoProto.internal_static_Classmate_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.xuan.protobuf_pojo.DemoProto.internal_static_Classmate_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.xuan.protobuf_pojo.DemoProto.Classmate.class, com.xuan.protobuf_pojo.DemoProto.Classmate.Builder.class);
    }

    public static final int NAME_FIELD_NUMBER = 1;
    private volatile java.lang.Object name_;
    /**
     * <pre>
     ** 名字 
     * </pre>
     *
     * <code>string name = 1;</code>
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      }
    }
    /**
     * <pre>
     ** 名字 
     * </pre>
     *
     * <code>string name = 1;</code>
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SEX_FIELD_NUMBER = 2;
    private boolean sex_;
    /**
     * <pre>
     ** 性别 
     * </pre>
     *
     * <code>bool sex = 2;</code>
     */
    public boolean getSex() {
      return sex_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, name_);
      }
      if (sex_ != false) {
        output.writeBool(2, sex_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, name_);
      }
      if (sex_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(2, sex_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.xuan.protobuf_pojo.DemoProto.Classmate)) {
        return super.equals(obj);
      }
      com.xuan.protobuf_pojo.DemoProto.Classmate other = (com.xuan.protobuf_pojo.DemoProto.Classmate) obj;

      if (!getName()
          .equals(other.getName())) return false;
      if (getSex()
          != other.getSex()) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + NAME_FIELD_NUMBER;
      hash = (53 * hash) + getName().hashCode();
      hash = (37 * hash) + SEX_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getSex());
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.xuan.protobuf_pojo.DemoProto.Classmate parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.xuan.protobuf_pojo.DemoProto.Classmate parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.xuan.protobuf_pojo.DemoProto.Classmate parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.xuan.protobuf_pojo.DemoProto.Classmate parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.xuan.protobuf_pojo.DemoProto.Classmate parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.xuan.protobuf_pojo.DemoProto.Classmate parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.xuan.protobuf_pojo.DemoProto.Classmate parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.xuan.protobuf_pojo.DemoProto.Classmate parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.xuan.protobuf_pojo.DemoProto.Classmate parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.xuan.protobuf_pojo.DemoProto.Classmate parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.xuan.protobuf_pojo.DemoProto.Classmate parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.xuan.protobuf_pojo.DemoProto.Classmate parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.xuan.protobuf_pojo.DemoProto.Classmate prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     ** 同学 
     * </pre>
     *
     * Protobuf type {@code Classmate}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Classmate)
        com.xuan.protobuf_pojo.DemoProto.ClassmateOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.xuan.protobuf_pojo.DemoProto.internal_static_Classmate_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.xuan.protobuf_pojo.DemoProto.internal_static_Classmate_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.xuan.protobuf_pojo.DemoProto.Classmate.class, com.xuan.protobuf_pojo.DemoProto.Classmate.Builder.class);
      }

      // Construct using com.xuan.protobuf_pojo.DemoProto.Classmate.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        name_ = "";

        sex_ = false;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.xuan.protobuf_pojo.DemoProto.internal_static_Classmate_descriptor;
      }

      @java.lang.Override
      public com.xuan.protobuf_pojo.DemoProto.Classmate getDefaultInstanceForType() {
        return com.xuan.protobuf_pojo.DemoProto.Classmate.getDefaultInstance();
      }

      @java.lang.Override
      public com.xuan.protobuf_pojo.DemoProto.Classmate build() {
        com.xuan.protobuf_pojo.DemoProto.Classmate result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.xuan.protobuf_pojo.DemoProto.Classmate buildPartial() {
        com.xuan.protobuf_pojo.DemoProto.Classmate result = new com.xuan.protobuf_pojo.DemoProto.Classmate(this);
        result.name_ = name_;
        result.sex_ = sex_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.xuan.protobuf_pojo.DemoProto.Classmate) {
          return mergeFrom((com.xuan.protobuf_pojo.DemoProto.Classmate)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.xuan.protobuf_pojo.DemoProto.Classmate other) {
        if (other == com.xuan.protobuf_pojo.DemoProto.Classmate.getDefaultInstance()) return this;
        if (!other.getName().isEmpty()) {
          name_ = other.name_;
          onChanged();
        }
        if (other.getSex() != false) {
          setSex(other.getSex());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.xuan.protobuf_pojo.DemoProto.Classmate parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.xuan.protobuf_pojo.DemoProto.Classmate) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object name_ = "";
      /**
       * <pre>
       ** 名字 
       * </pre>
       *
       * <code>string name = 1;</code>
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       ** 名字 
       * </pre>
       *
       * <code>string name = 1;</code>
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       ** 名字 
       * </pre>
       *
       * <code>string name = 1;</code>
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       ** 名字 
       * </pre>
       *
       * <code>string name = 1;</code>
       */
      public Builder clearName() {
        
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <pre>
       ** 名字 
       * </pre>
       *
       * <code>string name = 1;</code>
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        name_ = value;
        onChanged();
        return this;
      }

      private boolean sex_ ;
      /**
       * <pre>
       ** 性别 
       * </pre>
       *
       * <code>bool sex = 2;</code>
       */
      public boolean getSex() {
        return sex_;
      }
      /**
       * <pre>
       ** 性别 
       * </pre>
       *
       * <code>bool sex = 2;</code>
       */
      public Builder setSex(boolean value) {
        
        sex_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       ** 性别 
       * </pre>
       *
       * <code>bool sex = 2;</code>
       */
      public Builder clearSex() {
        
        sex_ = false;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:Classmate)
    }

    // @@protoc_insertion_point(class_scope:Classmate)
    private static final com.xuan.protobuf_pojo.DemoProto.Classmate DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.xuan.protobuf_pojo.DemoProto.Classmate();
    }

    public static com.xuan.protobuf_pojo.DemoProto.Classmate getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Classmate>
        PARSER = new com.google.protobuf.AbstractParser<Classmate>() {
      @java.lang.Override
      public Classmate parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Classmate(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Classmate> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Classmate> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.xuan.protobuf_pojo.DemoProto.Classmate getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Clazz_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Clazz_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Classmate_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Classmate_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\ndemo.proto\"&\n\005Clazz\022\035\n\tclassmate\030\001 \003(\013" +
      "2\n.Classmate\"&\n\tClassmate\022\014\n\004name\030\001 \001(\t\022" +
      "\013\n\003sex\030\002 \001(\010*R\n\nTargetType\022\017\n\013errorTarge" +
      "t\020\000\022\n\n\006ground\020\001\022\007\n\003sky\020\002\022\020\n\014groundAndSky" +
      "\020\003\022\014\n\010building\020\004B#\n\026com.xuan.protobuf_po" +
      "joB\tDemoProtob\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_Clazz_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Clazz_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Clazz_descriptor,
        new java.lang.String[] { "Classmate", });
    internal_static_Classmate_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_Classmate_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Classmate_descriptor,
        new java.lang.String[] { "Name", "Sex", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
